# Generated by Django 3.1.3 on 2020-12-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20201205_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='category',
            field=models.CharField(choices=[('PROF', 'Professional'), ('PHOT', 'Photography')], default='PHOT', max_length=4),
        ),
    ]
