# Generated by Django 3.1.3 on 2020-12-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_photo_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.CharField(choices=[('Professional', 'Professional'), ('Photography', 'Photography')], default='Photography', max_length=20),
        ),
    ]
