# Generated by Django 3.1.2 on 2020-12-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20201205_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='description',
            field=models.TextField(default='Hello world!'),
        ),
        migrations.AddField(
            model_name='photo',
            name='title',
            field=models.CharField(default='Hello world!', max_length=30),
        ),
    ]
